name: lint

on:
  push:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.x"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        id: install-deps
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -U -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Run Pyright
        uses: jakebailey/pyright-action@v1
        with:
          version: "1.1.351"
          warnings: false
          no-comments: ${{ matrix.python-version != '3.x' }}

      - name: Run black
        if: ${{ always() && steps.install-deps.outcome == 'success' }}
        run: |
          black --check django_app_router example

      - name: Run isort
        if: ${{ always() && steps.install-deps.outcome == 'success' }}
        run: |
          isort --check-only --balanced django_app_router example
